### PR TITLE
Update TZDB to 2018f and fix bug in TzdbZoneRulesCompiler that it triggers

### PR DESCRIPTION
**Pull request by Kiskae**
This PR fixes the issue mentioned in #94 and updates TZDB.dat to 2018f.

### CODE REVIEW

**Comment by Kiskae** [comment]
After considering it some more the correct behavior might be to replace `LocalTime time` with a duration signifying how long after midnight the change-over occurs. This would mean removing the `endOfDay` boolean field, `time` LocalTime field and refactoring quite a bit of the `org.threeten.bp.zone` package to handle a more generic "seconds after 0:00 on the specific day".

This would be backwards-compatible since the binary representation already stores the `time` field as either the number of hours or the number of seconds in the day. Changing this so it could go beyond one day is a trivial change. However this would not be forwards-compatible since old versions of the library would try to put the duration into a `LocalTime` object, causing the same error that lead to this commit when the user tries to load the database.

**Comment by jodastephen** [comment]
Thanks for looking into this. I think the change to use a `Duration` may be the right way to go, but it has to be approved in the JDK first (as this project copies the JDK API). In the short term I may merge this PR, although I haven't decided yet.

**Comment by Kiskae** [comment]
Besides additional factory methods to support the expanded range of values, the changes to the API would actually be pretty minor.

`getLocalTime()` is already normalized in relation to `isMidnightEndOfDay()`, so it might simply be a case of re-contextualizing it with a date offset:

- `getLocalTime()` - re-contextualize to be local time relative to the date offset.
- `getLocalTimeDateOffset()` - returns the date offset required by `getLocalTime()` relative to the day-of-week/day-of-month.
- `getLocalTimeDuration()` - for access to the exact cutover time relative to the date.
- `isMidnightEndOfDay()` (deprecated) - `getLocalTime()` is midnight and `getLocalTimeDateOffset()` is `1`.

Any users that is correctly using `getLocalTime` should already be checking `isMidnightEndOfDay` and will be alerted by the deprecation to use `getLocalTimeDateOffset` while other users are already experiencing potentially wrong results since they are not checking the context of `getLocalTime`.

**Comment by jodastephen** [comment]
I've merged this PR and taken ideas/code from your other branch to achieve a good outcome without changing the API. Hope that works for you.

**Pull request closed without merging**
