### PR TITLE
Fixes for the `Instant.truncatedTo` part of #53 

### PR DESCRIPTION
**Pull request by toadzky**
Fix for parts of the bugs mentioned in #53

### CODE REVIEW

**Comment by jodastephen** [comment]
The code looks good to fix the issue, but since there is still a broken test, I can't merge this PR. thanks.

**Comment by toadzky** [comment]
np. would you like me to comment out the breaking tests so it can be merged?

**Comment by jodastephen** [comment]
Yes, I think thats best

**Comment by toadzky** [comment]
Build is now passing

**Pull request merged**
